# Generated by Django 3.2.5 on 2021-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hs228M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_228_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs230M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_230_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
    ]
