# Generated by Django 3.2.5 on 2021-11-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startData', '0002_hs232m0809031355_hs273m0809031355_hs276m0809031355_hs315m0809031355_hs339m0809031355_hs341m080903135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hs477M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_477_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs479M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_479_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs486M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_486_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs488M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_488_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs490M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_490_m08_0903_1355',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hs492M0809031355',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('z', models.TextField(blank=True, db_column='Z', null=True)),
                ('act', models.TextField(blank=True, db_column='Act', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('message_1', models.TextField(blank=True, db_column='Message_1', null=True)),
                ('stt_1', models.TextField(blank=True, db_column='STT_1', null=True)),
                ('message_2', models.TextField(blank=True, db_column='Message_2', null=True)),
                ('stt_2', models.TextField(blank=True, db_column='STT_2', null=True)),
                ('message_3', models.TextField(blank=True, db_column='Message_3', null=True)),
                ('stt_3', models.TextField(blank=True, db_column='STT_3', null=True)),
            ],
            options={
                'db_table': 'hs_492_m08_0903_1355',
                'managed': False,
            },
        ),
    ]
